### ISSUE TITLE
Override nginx.conf with one in the git repo

### ISSUE THREAD

**Issue by dubcanada** [Scalingo/php-buildpack#16]
Hello,

It seems like it would be fairly easy to override the nginx.conf that is provided with one from the git repo just change https://github.com/Scalingo/php-buildpack/blob/master/bin/compile#L345 to see if one is set or not, if it is then use that one. Else fall back to the default.

Thoughts?

**Comment by Soulou** [comment]
You can already extend the configuration thanks to the `NGINX_INCLUDES` environment variable. Is it not enough?  https://github.com/Scalingo/php-buildpack/blob/master/conf/nginx/base.conf.erb#L77-L79 What are you not able to do?

It also leads to a few issues concerning the custom configuration for frameworks etc. As the base configuration is not a simple configuration file but a `.erb` file it is on some points difficult to allow the user to override it. We could improve ways to extend it I agree on that.

What is your use case?

**Comment by dubcanada** [comment]
I want to use it for Drupal dev, but I basically need to overwrite the entire base nginx conf. I want HTTPS, need to remove the gzip stuff, remove client_body stuff, tcp stuff, the entire site configuration, and replace it with the stuff Drupal requires.

I know I can extend the configuration, but I want to just use my version.

**Comment by dubcanada** [comment]
If you were to let people override it with what ever they want, it would let those who know what they are doing override it with their own config. And if you don't know what you are doing/what to use the base config. You can just not override it.

**Comment by Soulou** [comment]
Yes but in the `http` section, all the stuff you're quoting don't prevent a Drupal to run!

`gzip on` is to optimize the trafic between the server and the browser, Drupal doesn't care.
`client_body` is to set a limit on the uploaded files by the users.
`tcp_nopush` and `tcp_nodelay` don't modify Drupal behavior at all.

Actually you should be able to use it completely without any modification.

I've to precise the scope of this buildpack. It has been developed and is used to deploy PHP applications ono the PaaS Scalingo. These applications are not doing the SSH termination, another layer of request routing is doing it. That's why there is nothing builtin to handle HTTPS.

What does Drupal required which can't be done here?

**Comment by dubcanada** [comment]
Okay, I am not using this particular buildpack on Scalingo (require NA servers), and I already did the change (I require HTTPS termination, and the ability to change EVERYTHING). I was just wondering if you had any interest in having it merged back.

**Comment by Soulou** [comment]
Oh yeah, please create the pull request and then we'll speak about merging it into the project. I'm not against your proposition, I just want to be sure it has an interest and can be used in an interesting way by our users :)
