### ISSUE TITLE
Add event extension to the build pack

### ISSUE THREAD

**Issue by curzolapierre** [Scalingo/php-buildpack#178]
The `event` extension is asked by a customer from this conv: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700011748

Extension documentation: https://pecl.php.net/package/event

**Comment by EtienneM** [comment]
We currently support the `libevent` extension (https://pecl.php.net/package/libevent) as displayed on this documentation page: https://doc.scalingo.com/languages/php/start#list-of-available-extensions. But this `libevent` extension is deprecated since 2013.

The `event` extension (https://pecl.php.net/package/event) seems to be a replacement for this libevent extension. I think we should add it to the list of supported extension. It is actively maintained (last version date 2020-12-02) and is widely used (e.g. 810,869 downloads for the version 2.5.3).

**Comment by EtienneM** [comment]
Fixed by #179
