### ISSUE TITLE
Can't install default node version

### ISSUE THREAD

**Issue by SCedricThomas** [Scalingo/php-buildpack#381]
It is not possible to install the default node version:
```
-----> Defaulting to latest stable node: 21.4.0
+ echo '-----> Defaulting to latest stable node: 21.4.0'
+ status 'Downloading and installing node'
+ echo '-----> Downloading and installing node'
-----> Downloading and installing node
+ node_url=https://heroku-nodebin.s3.us-east-1.amazonaws.com/node/release/linux-x64/node-v21.4.0-linux-x64.tar.gz
+ curl https://heroku-nodebin.s3.us-east-1.amazonaws.com/node/release/linux-x64/node-v21.4.0-linux-x64.tar.gz --location -s -o -
+ tar xzf - -C /build/811f9103-b742-4e9b-ba57-88842c06d4f0
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Frzk** [comment]
The issue lies here: https://github.com/Scalingo/php-buildpack/blob/a61346aba4e64e670f91eb4adc541ce9b4c56534/lib/nodejs#L38

1. We check our semver to get the latest Node.js version available.
2. Our semver is updated. So, indeed, we try to install the latest version available.
3. But the Heroku repo we are using isn't up-to-date, so it fails.

We'll have to find a way to sync these versions.

**Comment by Frzk** [comment]
I see 2 ways to handle it:
1. Rely on Heroku's inventory file (https://github.com/heroku/heroku-buildpack-nodejs/blob/main/inventory/node.toml) rather than on our semver (which means we have to parse the .toml file and make sure we always retrieve the appropriate version).
2. Get rid of the Node.js setup in the PHP buildpack and advise to use a multi-buildpack instead.

WDYT?

**Comment by EtienneM** [comment]
@Frzk Maybe we could have a mix of the current situation and the first solution you suggest. Update the semver code so that the Node.js versions it uses are the ones from the Heroku TOML, WDYT?

I'm afraid that the second option would lead to a looooooooot of support.
